#!/bin/bash

echo 'Checking brew installation...'
which -s brew
if [[ $? != 0 ]] ; then
  # Install Homebrew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  brew update
fi

echo 'Checking brew packages...'
brew tap jakehilborn/jakehilborn 
brew install neovim tmux node rg fd ruby 

echo 'Checking brew casks...'
brew tap homebrew/cask-fonts
brew install --cask brave-browser signal iterm2 font-hack-nerd-font

echo 'Bootstrapping complete.'
