#!/bin/bash

apt update -y 
apt upgrade -y
apt dist-upgrade -y

apt install unattended-upgrades -y
dpkg-reconfigure --priority=low unattended-upgrades

# Install Firewall
apt install ufw -y
ufw default deny incoming 
ufw default allow outgoing 
ufw allow ssh
echo "y" | ufw enable

# Install docker
curl -sSL https://get.docker.com | sh
usermod -aG docker $USER

reboot
