#!/bin/bash

echo 'Checking brew installation...'
which -s brew
if [[ $? != 0 ]] ; then
  # Install Homebrew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  brew update
fi

echo 'Checking brew packages...'
for package in neovim tmux node rg fd ruby
do 
  if ! brew info $package &>/dev/null; then
    brew install $package
  fi
done

echo 'Checking brew casks...'
for cask in brave-browser signal
do 
  if ! brew info $cask &>/dev/null; then
    brew install --cask $cask
  fi
done

echo 'Installing display-placer...'
if ! brew info displayplacer &>/dev/null; then
  brew tap jakehilborn/jakehilborn && brew install displayplacer
fi

echo 'Bootstrapping complete.'
