#!/bin/bash

echo 'Checking brew installation...'
which -s brew
if [[ $? != 0 ]] ; then
  # Install Homebrew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  brew update
fi

echo 'Checking brew packages...'
brew tap jakehilborn/jakehilborn 
for package in neovim tmux node rg fd ruby displayplacer
do 
  if ! brew info $package &>/dev/null; then
    brew install $package
  fi
done

echo 'Checking brew casks...'
brew tap homebrew/cask-fonts
for cask in brave-browser signal iterm2 font-hack-nerd-font
do 
  if ! brew info $cask &>/dev/null; then
    brew install --cask $cask
  fi
done

echo 'Bootstrapping complete.'
