theme = 'dark_plus'

[editor]
true-color = true
bufferline = 'always'
line-number = 'relative'
# auto-info = false

[keys.normal]
C-j = 'goto_next_diag'
C-k = 'goto_prev_diag'
L = 'goto_next_buffer'
H = 'goto_previous_buffer'
esc = ['collapse_selection', 'keep_primary_selection']

[editor.cursor-shape]
insert = 'bar'
